<?php
/**.-------------------------------------------------------------------------------------------------------------------
 * |  Github: https://github.com/Tinywan
 * |  Blog: http://www.cnblogs.com/Tinywan
 * |--------------------------------------------------------------------------------------------------------------------
 * |  Author: Tinywan(ShaoBo Wan)
 * |  DateTime: 2018/8/21 15:51
 * |  Mail: Overcome.wan@Gmail.com
 * |  Desc: 汇付宝通道
 * '------------------------------------------------------------------------------------------------------------------*/
namespace app\common\repositories\channel;


use app\common\repositories\contracts\ChannelRepositoryAbstract;
use think\facade\Log;

class HeePay extends ChannelRepositoryAbstract
{
    public function gateWay($option)
    {
        parent::gateWay($option); // TODO: Change the autogenerated stub
        Log::debug("汇付宝渠道");
        return $this->setError(false,"渠道已关闭");
    }
}