<?php
/**
 * Created by PhpStorm.
 * User: tinyw
 * Date: 2018/8/22
 * Time: 11:22
 */

namespace app\common\repositories\channel;

use app\common\repositories\contracts\ChannelRepositoryAbstract;
use think\facade\Log;

class SandPay extends ChannelRepositoryAbstract
{
    public function gateWay($option)
    {
        parent::gateWay($option); // TODO: Change the autogenerated stub
        Log::debug("杉得的通道");
        return $this->setError(false,"渠道已关闭");
    }
}