<?php
/**
 * Created by PhpStorm.
 * User: tinyw
 * Date: 2018/8/22
 * Time: 10:25
 */

namespace app\common\services\payment;

use app\common\services\contracts\PaymentServiceAbstract;

class GateWay extends PaymentServiceAbstract
{
    public function gateWay($params)
    {
        parent::gateWay($params); // TODO: Change the autogenerated stub
        $this->channel->gateWay($params);
    }
}